#!/usr/bin/env sh

# taps
brew tap homebrew/binary
brew tap homebrew/boneyard
brew tap homebrew/completions
brew tap homebrew/core
brew tap homebrew/fuse
brew tap homebrew/games
brew tap homebrew/python
brew tap homebrew/science
brew tap homebrew/services
brew tap homebrew/x11
brew tap mpv-player/mpv
brew tap neovim/neovim
brew tap railwaycat/emacsmacport
brew tap rstacruz/backup

# packages
brew install aircrack-ng
brew install android-platform-tools
brew install ant
brew install apache-spark
brew install aspell
brew install autoconf
brew install automake
brew install bazel
brew install boost
brew install byobu
brew install cairo
brew install chromedriver
brew install clang-omp
brew install cloc
brew install cloog
brew install cmake
brew install coreutils
brew install ctags
brew install doxygen
brew install eigen
brew install emacs-mac
brew install exercism
brew install fasd
brew install ffmpeg
brew install ffms2
brew install fftw
brew install fish
brew install flac
brew install fontconfig
brew install freetype
brew install fribidi
brew install gcc
brew install gdbm
brew install gettext
brew install gfortran
brew install git
brew install glib
brew install gmp
brew install gnu-sed
brew install gnu-typist
brew install gnutls
brew install go
brew install gobject-introspection
brew install harfbuzz
brew install highlight
brew install htop-osx
brew install icu4c
brew install ilmbase
brew install intltool
brew install irssi
brew install isl
brew install jansson
brew install jpeg
brew install jrnl
brew install kwm
brew install lame
brew install leptonica
brew install libass
brew install libbs2b
brew install libconfig
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libidn
brew install libiomp
brew install libmpc
brew install libogg
brew install libpng
brew install libsndfile
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libvo-aacenc
brew install libvorbis
brew install little-cms2
brew install lua
brew install luajit
brew install makedepend
brew install maven
brew install mercurial
brew install midnight-commander
brew install mobile-shell
brew install mongodb
brew install mpfr
brew install mpv
brew install mpw
brew install mtr
brew install mupdf
brew install mvtools
brew install namebench
brew install ncdu
brew install neovim
brew install net-snmp
brew install nettle
brew install newt
brew install node
brew install numpy
brew install open-mpi
brew install opencv3
brew install openexr
brew install openssl
brew install pacvim
brew install pandoc
brew install pcre
brew install pcre2
brew install phantomjs
brew install pixman
brew install pkg-config
brew install popt
brew install postgresql
brew install protobuf
brew install pyenv
brew install pyenv-virtualenv
brew install pyenv-virtualenvwrapper
brew install python
brew install python3
brew install qt5
brew install ranger
brew install readline
brew install rtmpdump
brew install s-lang
brew install scipy
brew install sonar-runner
brew install speedtest_cli
brew install spin
brew install sqlite
brew install ssh-copy-id
brew install subliminal
brew install swig
brew install task
brew install tbb
brew install tesseract
brew install texi2html
brew install theora
brew install tmux
brew install tokyo-cabinet
brew install tree
brew install typespeed
brew install vagrant-completion
brew install vapoursynth
brew install vim
brew install vit
brew install webp
brew install wget
brew install whereami
brew install x264
brew install x265
brew install xhyve
brew install xmlstarlet
brew install xspin
brew install xvid
brew install xz
brew install yasm
brew install youtube-dl
brew install zeromq
brew install zimg
brew install zsh
brew install zsh-syntax-highlighting
