# OH-MY-ZSH CONFIG
# export ZSH=$HOME/.oh-my-zsh

# ZSH_THEME="terminalparty"

# plugins=(colored-man-pages emoji\
#   vi-mode extract fasd zsh-autosuggestions history-substring-search)

# DISABLE_UPDATE_PROMPT=true

# source $ZSH/oh-my-zsh.sh

# PERSONAL CONFIG

# source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# bindkey -v

# zstyle ':completion:*:manuals'    separate-sections true
# zstyle ':completion:*:manuals.*'  insert-sections   true
# zstyle ':completion:*:man:*'      menu yes select

# export GOPATH=$HOME/projects/go
# export PATH=~/bin:${GOPATH}/bin:/Developer/NVIDIA/CUDA-8.0/bin${PATH:+:${PATH}}
# export CUDA_HOME=/Developer/NVIDIA/CUDA-8.0

# export HOMEBREW_GITHUB_API_TOKEN="b9d66b79be21463eed1b679b2712fc9cdad339cc"

# export PROJECT_HOME="$HOME/projects"
# eval "$(pyenv virtualenv-init -)"

export VISUAL=vim
export EDITOR=vim
export PAGER=vimpager
export TERM=xterm-256color
export BYOBU_PREFIX=$(brew --prefix)
export MP_FULLNAME="Arthur Tazhitdinov"
export SONAR_RUNNER_HOME=/usr/local/Cellar/sonar-runner/2.5/libexec
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export CHEATCOLORS=true
export XDG_CONFIG_HOME=$HOME/.config
export ZCODE_PATH=$HOME/Dropbox/Games/IF/
export LPASS_HOME=$XDG_CONFIG_HOME/lpass

alias zshconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.vimrc"
alias tmuxconfig="vim ~/.tmux.conf"
alias ohmyzsh="vim ~/.oh-my-zsh"
#alias tmux="tmux -2"
alias sshhome="ssh -p 2222 arthur@467859.dyn.ufanet.ru"
alias t="~/Dropbox/Bin/todo.txt-cli/todo.sh -tnA -d ~/Dropbox/Bin/todo.txt-cli/todo.cfg"
alias zshreload="source ~/.zshrc"
alias speed="speedtest-cli --mini http://v.ufanet.ru/"
alias wifi='osx-wifi-cli'
alias frotz='frotz -l 3 -r 3'

export KEYTIMEOUT=1

# #source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"
# source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
# source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

# #source ~/dotfiles/zsh/shell_prompt.sh

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
# # activate zsh-completions
#fpath=(/usr/local/share/zsh-completions $fpath)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

profile-switch () { echo -e "\033]50;SetProfile=$1\a"; export ITERM_PROFILE=$1; }

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

ssh() {
    if [ "$(ps -p $(ps -p $$ -o ppid=) -o comm=)" = "tmux" ]; then
        tmux rename-window "$(echo $* | rev | cut -d ' ' -f1 | rev | cut -d . -f 1)"
        command ssh "$@"
        tmux set-window-option automatic-rename "on" 1>/dev/null
    else
        command ssh "$@"
    fi
}

bindkey -M viins 'jj' vi-cmd-mode
bindkey -e jj \\e

# Use vim cli mode
bindkey '^P' up-history
bindkey '^N' down-history

# backspace and ^h working even after
# returning from command mode
#bindkey '^?' backward-delete-char
#bindkey '^h' backward-delete-char

# ctrl-w removed word backwards
#bindkey '^w' backward-kill-word

# ctrl-r starts searching history backward
#bindkey '^r' history-incremental-search-backward

# eval "$(thefuck --alias)"
# eval "$(hub alias -s)"

# export PATH="/usr/local/sbin:$PATH"

# Initialise zulu plugin manager
source "${ZULU_DIR:-"${ZDOTDIR:-$HOME}/.zulu"}/core/zulu"
zulu init
