# OH-MY-ZSH CONFIG
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="terminalparty"

plugins=(git colored-man-pages emoji nyan systemadmin go docker docker-compose\
  vi-mode extract osx brew fasd zsh-autosuggestions history-substring-search\
  pip pyenv pylint python vagrant virtualenv virtualenvwrapper\
  zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# PERSONAL CONFIG

bindkey -v

zstyle ':completion:*:manuals'    separate-sections true
zstyle ':completion:*:manuals.*'  insert-sections   true
zstyle ':completion:*:man:*'      menu yes select

export PATH=~/bin:/Developer/NVIDIA/CUDA-8.0/bin${PATH:+:${PATH}}
export CUDA_HOME=/Developer/NVIDIA/CUDA-8.0

export HOMEBREW_GITHUB_API_TOKEN="b9d66b79be21463eed1b679b2712fc9cdad339cc"
export GOPATH=$HOME/projects/go

export PROJECT_HOME="$HOME/projects"
eval "$(pyenv virtualenv-init -)"

export VISUAL=vim
export EDITOR=vim
#export TERM=xterm-256color
export BYOBU_PREFIX=$(brew --prefix)
export MP_FULLNAME="Arthur Tazhitdinov"
export SONAR_RUNNER_HOME=/usr/local/Cellar/sonar-runner/2.5/libexec
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

alias zshconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.vimrc"
alias tmuxconfig="vim ~/.tmux.conf"
alias ohmyzsh="vim ~/.oh-my-zsh"
#alias tmux="tmux -2"
alias sshhome="ssh -p 2222 arthur@467859.dyn.ufanet.ru"
alias t="~/Dropbox/Bin/todo.txt-cli/todo.sh -tnA -d ~/Dropbox/Bin/todo.txt-cli/todo.cfg"
alias zshreload="source ~/.zshrc"
alias speed="speedtest-cli --mini http://v.ufanet.ru/"

source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

#source ~/dotfiles/zsh/shell_prompt.sh

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
fpath=(/usr/local/share/zsh-completions $fpath)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

profile-switch () { echo -e "\033]50;SetProfile=$1\a"; export ITERM_PROFILE=$1; }

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

ssh() {
    if [ "$(ps -p $(ps -p $$ -o ppid=) -o comm=)" = "tmux" ]; then
        tmux rename-window "$(echo $* | rev | cut -d ' ' -f1 | rev | cut -d . -f 1)"
        command ssh "$@"
        tmux set-window-option automatic-rename "on" 1>/dev/null
    else
        command ssh "$@"
    fi
}

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

